application: smart-closet
version: 3
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /.*
  script: main.py
  login: required


libraries:

- name: webapp2
  version: "2.5.2"
